var seqz = {
    "id": 0000,
    "Player1": "Uschi",
    "Player2": "Ulli",
    "User": false,
    "Timer": 60,
    "Fragen": [null],
    "answers1": [],
    "answers2": [],
    "response1": [],
    "response2": [],
    "result": [],
    "match": [],
    "match1": [],
    "match2": [],
    "time": [],
    "time1": [],
    "time2": [],
    "timeBonus1" : [],
    "timeBonus2" : [],
    "timeBonus" : [],
    "score" : null,
    "activeIndex": -1,
    "readyIndex": -1
}
